### ISSUE TITLE
Placeholder Silently Fails for non-string Options

### ISSUE THREAD

**Issue by elithrar** [ziuchkovski/writ#1]
Setting a `placeholder:"<some-thing>" as a struct tag for types other than `string` causes the option parsing to silently fail and omit that option:

```go
type Config struct {
	# Included
	Start     int64  `option:"start-time" description:"The timestamp (in Unix seconds) to request logs from."`
	# Omitted (i.e. not parsed, not included in help text)
	End       int64  `option:"end-time" placeholder="<unix-timestamp>" description:"The timestamp (in Unix seconds) to request logs to."`
	# Included	Count     int    `option:"c, count" default:"1" description:"The number (count) of logs to retrieve."`
}
```

Is this intended? Can be useful to describe formatting.

**Comment by ziuchkovski** [comment]
@elithrar I think the error is actually the formatting on the struct tag.  End has `placeholder=` instead of `placeholder:`.  The struct tag parsing provided by the reflect package silently ignores/omits tags that are malformed.  It makes no attempt to recover or inform you of the issue, so on the writ side it just looks to writ like the `placeholder` tag doesn't exist.

**Comment by elithrar** [comment]
Whoops—totally looked past that. Thanks for the quick response!

**Comment by ziuchkovski** [comment]
No problem!
